name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Sostituisci con il branch corretto se usi un altro branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate config.js with API key
        run: echo "var API_KEY = '${{ secrets.API_CONFIG_FIREBASE }}';" > config.js

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: .
          production-branch: main
          deploy-message: "GitHub Actions Deploy"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
