name: Deploy to Netlify

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Generate config.js with API key
        run: echo "var API_KEY = '${{ secrets.API_CONFIG_FIREBASE }}';" > config.js

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=.
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

