name: Deploy to Netlify

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment Variables
        run: echo "API_CONFIGURE_FIREBASE: ${{ secrets.API_CONFIGURE_FIREBASE }}"

      - name: Build
        env:
          API_KEY: ${{ secrets.API_CONFIGURE_FIREBASE }}
        run: |
          npm install
          npm run build

