name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        env:
          API_KEY: ${{ secrets.API_CONFIG_FIREBASE }}
        run: |
          npm install
          npm run build
